spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  application:
    name: Workshop_Angeles
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
