spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    #url: jdbc:mysql://localhost:3306/test
    url: jdbc:postgresql://10.10.25.157:5432/postgres?currentSchema=antonio
    username: postgres
    password: 23People
  application:
    name: Workshop_Antonio
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
