spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 23people
  application:
    name: Workshop_Antonio
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
